export const red = "#FF2F54";
export const blue = "#2191FB";
export const blueGreen = "#B2ECE1";
export const green = "rgb(109, 187, 26)";
export const yellow = "#FFF8E5";
export const greenDarkBlue = "#8CDEDC";
export const darkBlue = "#011936";
export const orange = "orange";
export const black = "black";
